// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.4
// - protoc             v3.12.4
// source: app/v1/analytics_job.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationAnalyticsJobCreateAnalyticsJob = "/api.app.v1.AnalyticsJob/CreateAnalyticsJob"
const OperationAnalyticsJobGetAnalyticsJob = "/api.app.v1.AnalyticsJob/GetAnalyticsJob"
const OperationAnalyticsJobListAnalyticsJob = "/api.app.v1.AnalyticsJob/ListAnalyticsJob"

type AnalyticsJobHTTPServer interface {
	CreateAnalyticsJob(context.Context, *CreateAnalyticsJobRequest) (*CreateAnalyticsJobReply, error)
	GetAnalyticsJob(context.Context, *GetAnalyticsJobRequest) (*GetAnalyticsJobReply, error)
	ListAnalyticsJob(context.Context, *ListAnalyticsJobRequest) (*ListAnalyticsJobReply, error)
}

func RegisterAnalyticsJobHTTPServer(s *http.Server, srv AnalyticsJobHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/analytics-job", _AnalyticsJob_CreateAnalyticsJob0_HTTP_Handler(srv))
	r.GET("/v1/analytics-job/{id}", _AnalyticsJob_GetAnalyticsJob0_HTTP_Handler(srv))
	r.GET("/v1/analytics-job", _AnalyticsJob_ListAnalyticsJob0_HTTP_Handler(srv))
}

func _AnalyticsJob_CreateAnalyticsJob0_HTTP_Handler(srv AnalyticsJobHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateAnalyticsJobRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAnalyticsJobCreateAnalyticsJob)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateAnalyticsJob(ctx, req.(*CreateAnalyticsJobRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateAnalyticsJobReply)
		return ctx.Result(200, reply)
	}
}

func _AnalyticsJob_GetAnalyticsJob0_HTTP_Handler(srv AnalyticsJobHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetAnalyticsJobRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAnalyticsJobGetAnalyticsJob)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetAnalyticsJob(ctx, req.(*GetAnalyticsJobRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetAnalyticsJobReply)
		return ctx.Result(200, reply)
	}
}

func _AnalyticsJob_ListAnalyticsJob0_HTTP_Handler(srv AnalyticsJobHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListAnalyticsJobRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAnalyticsJobListAnalyticsJob)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListAnalyticsJob(ctx, req.(*ListAnalyticsJobRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListAnalyticsJobReply)
		return ctx.Result(200, reply)
	}
}

type AnalyticsJobHTTPClient interface {
	CreateAnalyticsJob(ctx context.Context, req *CreateAnalyticsJobRequest, opts ...http.CallOption) (rsp *CreateAnalyticsJobReply, err error)
	GetAnalyticsJob(ctx context.Context, req *GetAnalyticsJobRequest, opts ...http.CallOption) (rsp *GetAnalyticsJobReply, err error)
	ListAnalyticsJob(ctx context.Context, req *ListAnalyticsJobRequest, opts ...http.CallOption) (rsp *ListAnalyticsJobReply, err error)
}

type AnalyticsJobHTTPClientImpl struct {
	cc *http.Client
}

func NewAnalyticsJobHTTPClient(client *http.Client) AnalyticsJobHTTPClient {
	return &AnalyticsJobHTTPClientImpl{client}
}

func (c *AnalyticsJobHTTPClientImpl) CreateAnalyticsJob(ctx context.Context, in *CreateAnalyticsJobRequest, opts ...http.CallOption) (*CreateAnalyticsJobReply, error) {
	var out CreateAnalyticsJobReply
	pattern := "/v1/analytics-job"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAnalyticsJobCreateAnalyticsJob))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AnalyticsJobHTTPClientImpl) GetAnalyticsJob(ctx context.Context, in *GetAnalyticsJobRequest, opts ...http.CallOption) (*GetAnalyticsJobReply, error) {
	var out GetAnalyticsJobReply
	pattern := "/v1/analytics-job/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAnalyticsJobGetAnalyticsJob))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AnalyticsJobHTTPClientImpl) ListAnalyticsJob(ctx context.Context, in *ListAnalyticsJobRequest, opts ...http.CallOption) (*ListAnalyticsJobReply, error) {
	var out ListAnalyticsJobReply
	pattern := "/v1/analytics-job"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAnalyticsJobListAnalyticsJob))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
