// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: app/v1/analytics_job.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnalyticsJobModel struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedTime     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	LastUpdatedTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_updated_time,json=lastUpdatedTime,proto3" json:"last_updated_time,omitempty"`
	Latitude        float64                `protobuf:"fixed64,4,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude       float64                `protobuf:"fixed64,5,opt,name=longitude,proto3" json:"longitude,omitempty"`
	FileUrl         string                 `protobuf:"bytes,6,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
	VideoUrl        string                 `protobuf:"bytes,7,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	Status          string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	Result          string                 `protobuf:"bytes,9,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AnalyticsJobModel) Reset() {
	*x = AnalyticsJobModel{}
	mi := &file_app_v1_analytics_job_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyticsJobModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyticsJobModel) ProtoMessage() {}

func (x *AnalyticsJobModel) ProtoReflect() protoreflect.Message {
	mi := &file_app_v1_analytics_job_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyticsJobModel.ProtoReflect.Descriptor instead.
func (*AnalyticsJobModel) Descriptor() ([]byte, []int) {
	return file_app_v1_analytics_job_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyticsJobModel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AnalyticsJobModel) GetCreatedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedTime
	}
	return nil
}

func (x *AnalyticsJobModel) GetLastUpdatedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdatedTime
	}
	return nil
}

func (x *AnalyticsJobModel) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *AnalyticsJobModel) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *AnalyticsJobModel) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *AnalyticsJobModel) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

func (x *AnalyticsJobModel) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AnalyticsJobModel) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type CreateAnalyticsJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	FileUrl       string                 `protobuf:"bytes,3,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
	VideoUrl      string                 `protobuf:"bytes,4,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAnalyticsJobRequest) Reset() {
	*x = CreateAnalyticsJobRequest{}
	mi := &file_app_v1_analytics_job_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAnalyticsJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAnalyticsJobRequest) ProtoMessage() {}

func (x *CreateAnalyticsJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_v1_analytics_job_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAnalyticsJobRequest.ProtoReflect.Descriptor instead.
func (*CreateAnalyticsJobRequest) Descriptor() ([]byte, []int) {
	return file_app_v1_analytics_job_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAnalyticsJobRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *CreateAnalyticsJobRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *CreateAnalyticsJobRequest) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *CreateAnalyticsJobRequest) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

type CreateAnalyticsJobReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *AnalyticsJobModel     `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAnalyticsJobReply) Reset() {
	*x = CreateAnalyticsJobReply{}
	mi := &file_app_v1_analytics_job_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAnalyticsJobReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAnalyticsJobReply) ProtoMessage() {}

func (x *CreateAnalyticsJobReply) ProtoReflect() protoreflect.Message {
	mi := &file_app_v1_analytics_job_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAnalyticsJobReply.ProtoReflect.Descriptor instead.
func (*CreateAnalyticsJobReply) Descriptor() ([]byte, []int) {
	return file_app_v1_analytics_job_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAnalyticsJobReply) GetData() *AnalyticsJobModel {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetAnalyticsJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnalyticsJobRequest) Reset() {
	*x = GetAnalyticsJobRequest{}
	mi := &file_app_v1_analytics_job_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnalyticsJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnalyticsJobRequest) ProtoMessage() {}

func (x *GetAnalyticsJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_v1_analytics_job_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnalyticsJobRequest.ProtoReflect.Descriptor instead.
func (*GetAnalyticsJobRequest) Descriptor() ([]byte, []int) {
	return file_app_v1_analytics_job_proto_rawDescGZIP(), []int{3}
}

func (x *GetAnalyticsJobRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAnalyticsJobReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *AnalyticsJobModel     `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnalyticsJobReply) Reset() {
	*x = GetAnalyticsJobReply{}
	mi := &file_app_v1_analytics_job_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnalyticsJobReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnalyticsJobReply) ProtoMessage() {}

func (x *GetAnalyticsJobReply) ProtoReflect() protoreflect.Message {
	mi := &file_app_v1_analytics_job_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnalyticsJobReply.ProtoReflect.Descriptor instead.
func (*GetAnalyticsJobReply) Descriptor() ([]byte, []int) {
	return file_app_v1_analytics_job_proto_rawDescGZIP(), []int{4}
}

func (x *GetAnalyticsJobReply) GetData() *AnalyticsJobModel {
	if x != nil {
		return x.Data
	}
	return nil
}

type ListAnalyticsJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int64                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAnalyticsJobRequest) Reset() {
	*x = ListAnalyticsJobRequest{}
	mi := &file_app_v1_analytics_job_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAnalyticsJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAnalyticsJobRequest) ProtoMessage() {}

func (x *ListAnalyticsJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_v1_analytics_job_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAnalyticsJobRequest.ProtoReflect.Descriptor instead.
func (*ListAnalyticsJobRequest) Descriptor() ([]byte, []int) {
	return file_app_v1_analytics_job_proto_rawDescGZIP(), []int{5}
}

func (x *ListAnalyticsJobRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListAnalyticsJobRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListAnalyticsJobReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*AnalyticsJobModel   `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAnalyticsJobReply) Reset() {
	*x = ListAnalyticsJobReply{}
	mi := &file_app_v1_analytics_job_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAnalyticsJobReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAnalyticsJobReply) ProtoMessage() {}

func (x *ListAnalyticsJobReply) ProtoReflect() protoreflect.Message {
	mi := &file_app_v1_analytics_job_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAnalyticsJobReply.ProtoReflect.Descriptor instead.
func (*ListAnalyticsJobReply) Descriptor() ([]byte, []int) {
	return file_app_v1_analytics_job_proto_rawDescGZIP(), []int{6}
}

func (x *ListAnalyticsJobReply) GetData() []*AnalyticsJobModel {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListAnalyticsJobReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_app_v1_analytics_job_proto protoreflect.FileDescriptor

const file_app_v1_analytics_job_proto_rawDesc = "" +
	"\n" +
	"\x1aapp/v1/analytics_job.proto\x12\n" +
	"api.app.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\"\xcc\x02\n" +
	"\x11AnalyticsJobModel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12=\n" +
	"\fcreated_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vcreatedTime\x12F\n" +
	"\x11last_updated_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x0flastUpdatedTime\x12\x1a\n" +
	"\blatitude\x18\x04 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x05 \x01(\x01R\tlongitude\x12\x19\n" +
	"\bfile_url\x18\x06 \x01(\tR\afileUrl\x12\x1b\n" +
	"\tvideo_url\x18\a \x01(\tR\bvideoUrl\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x16\n" +
	"\x06result\x18\t \x01(\tR\x06result\"\x8d\x01\n" +
	"\x19CreateAnalyticsJobRequest\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x19\n" +
	"\bfile_url\x18\x03 \x01(\tR\afileUrl\x12\x1b\n" +
	"\tvideo_url\x18\x04 \x01(\tR\bvideoUrl\"L\n" +
	"\x17CreateAnalyticsJobReply\x121\n" +
	"\x04data\x18\x01 \x01(\v2\x1d.api.app.v1.AnalyticsJobModelR\x04data\"(\n" +
	"\x16GetAnalyticsJobRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"I\n" +
	"\x14GetAnalyticsJobReply\x121\n" +
	"\x04data\x18\x01 \x01(\v2\x1d.api.app.v1.AnalyticsJobModelR\x04data\"G\n" +
	"\x17ListAnalyticsJobRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\"`\n" +
	"\x15ListAnalyticsJobReply\x121\n" +
	"\x04data\x18\x01 \x03(\v2\x1d.api.app.v1.AnalyticsJobModelR\x04data\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total2\xfe\x02\n" +
	"\fAnalyticsJob\x12~\n" +
	"\x12CreateAnalyticsJob\x12%.api.app.v1.CreateAnalyticsJobRequest\x1a#.api.app.v1.CreateAnalyticsJobReply\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/analytics-job\x12w\n" +
	"\x0fGetAnalyticsJob\x12\".api.app.v1.GetAnalyticsJobRequest\x1a .api.app.v1.GetAnalyticsJobReply\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/analytics-job/{id}\x12u\n" +
	"\x10ListAnalyticsJob\x12#.api.app.v1.ListAnalyticsJobRequest\x1a!.api.app.v1.ListAnalyticsJobReply\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/analytics-jobBG\n" +
	"\n" +
	"api.app.v1P\x01Z7github.com/ntquang98/go-rkinetics-service/api/app/v1;v1b\x06proto3"

var (
	file_app_v1_analytics_job_proto_rawDescOnce sync.Once
	file_app_v1_analytics_job_proto_rawDescData []byte
)

func file_app_v1_analytics_job_proto_rawDescGZIP() []byte {
	file_app_v1_analytics_job_proto_rawDescOnce.Do(func() {
		file_app_v1_analytics_job_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_v1_analytics_job_proto_rawDesc), len(file_app_v1_analytics_job_proto_rawDesc)))
	})
	return file_app_v1_analytics_job_proto_rawDescData
}

var file_app_v1_analytics_job_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_app_v1_analytics_job_proto_goTypes = []any{
	(*AnalyticsJobModel)(nil),         // 0: api.app.v1.AnalyticsJobModel
	(*CreateAnalyticsJobRequest)(nil), // 1: api.app.v1.CreateAnalyticsJobRequest
	(*CreateAnalyticsJobReply)(nil),   // 2: api.app.v1.CreateAnalyticsJobReply
	(*GetAnalyticsJobRequest)(nil),    // 3: api.app.v1.GetAnalyticsJobRequest
	(*GetAnalyticsJobReply)(nil),      // 4: api.app.v1.GetAnalyticsJobReply
	(*ListAnalyticsJobRequest)(nil),   // 5: api.app.v1.ListAnalyticsJobRequest
	(*ListAnalyticsJobReply)(nil),     // 6: api.app.v1.ListAnalyticsJobReply
	(*timestamppb.Timestamp)(nil),     // 7: google.protobuf.Timestamp
}
var file_app_v1_analytics_job_proto_depIdxs = []int32{
	7, // 0: api.app.v1.AnalyticsJobModel.created_time:type_name -> google.protobuf.Timestamp
	7, // 1: api.app.v1.AnalyticsJobModel.last_updated_time:type_name -> google.protobuf.Timestamp
	0, // 2: api.app.v1.CreateAnalyticsJobReply.data:type_name -> api.app.v1.AnalyticsJobModel
	0, // 3: api.app.v1.GetAnalyticsJobReply.data:type_name -> api.app.v1.AnalyticsJobModel
	0, // 4: api.app.v1.ListAnalyticsJobReply.data:type_name -> api.app.v1.AnalyticsJobModel
	1, // 5: api.app.v1.AnalyticsJob.CreateAnalyticsJob:input_type -> api.app.v1.CreateAnalyticsJobRequest
	3, // 6: api.app.v1.AnalyticsJob.GetAnalyticsJob:input_type -> api.app.v1.GetAnalyticsJobRequest
	5, // 7: api.app.v1.AnalyticsJob.ListAnalyticsJob:input_type -> api.app.v1.ListAnalyticsJobRequest
	2, // 8: api.app.v1.AnalyticsJob.CreateAnalyticsJob:output_type -> api.app.v1.CreateAnalyticsJobReply
	4, // 9: api.app.v1.AnalyticsJob.GetAnalyticsJob:output_type -> api.app.v1.GetAnalyticsJobReply
	6, // 10: api.app.v1.AnalyticsJob.ListAnalyticsJob:output_type -> api.app.v1.ListAnalyticsJobReply
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_app_v1_analytics_job_proto_init() }
func file_app_v1_analytics_job_proto_init() {
	if File_app_v1_analytics_job_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_v1_analytics_job_proto_rawDesc), len(file_app_v1_analytics_job_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_v1_analytics_job_proto_goTypes,
		DependencyIndexes: file_app_v1_analytics_job_proto_depIdxs,
		MessageInfos:      file_app_v1_analytics_job_proto_msgTypes,
	}.Build()
	File_app_v1_analytics_job_proto = out.File
	file_app_v1_analytics_job_proto_goTypes = nil
	file_app_v1_analytics_job_proto_depIdxs = nil
}
