// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/ntquang98/go-rkinetics-service/internal/biz"
	"github.com/ntquang98/go-rkinetics-service/internal/conf"
	"github.com/ntquang98/go-rkinetics-service/internal/data"
	"github.com/ntquang98/go-rkinetics-service/internal/server"
	"github.com/ntquang98/go-rkinetics-service/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logger)
	greeterService := service.NewGreeterService(greeterUsecase)
	grpcServer := server.NewGRPCServer(confServer, greeterService, logger)
	fileRepo := data.NewS3FileRepo(confData, logger)
	fileUsecase := biz.NewFileUsecase(fileRepo, logger)
	fileService := service.NewFileService(fileUsecase, logger)
	analyticsJobRepo := data.NewAnalyticsJobRepo(dataData, logger)
	analyticsJobUsecase := biz.NewAnalyticsJobUsecase(analyticsJobRepo, logger)
	analyticsJobService := service.NewAnalyticsJobService(analyticsJobUsecase, logger)
	httpServer := server.NewHTTPServer(confServer, greeterService, fileService, analyticsJobService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
